---
- name: "include next_snapshot_incremental_local_archive_yml = {{ next_snapshot_incremental_local_archive_yml }}"
  include_vars:
    file: "{{ cassandra22x_restore_vars }}/{{ cassandra22x_environment }}/{{ inventory_hostname }}/{{ next_snapshot_incremental_local_archive_yml }}"
  delegate_to: 127.0.0.1

- name: "create a blank list of all next_snapshot_keyspace_ymls for the snapshot_{{ snapshot_uuid }}"
  set_fact:
    next_snapshot_keyspace_ymls: []
    
- name: "fill the list of all the next_snapshot_keyspace_ymls for the snapshot_{{ snapshot_uuid }}"
  set_fact:
    next_snapshot_keyspace_ymls: "{{ next_snapshot_keyspace_ymls }} + [ 'snapshot_{{ snapshot_uuid }}_{{ item }}.yml' ]"
  with_items: "{{ keyspace_names }}"    

- name: "include snapshot_incremental_local_archive_yml = {{ snapshot_incremental_local_archive_yml }}"
  include_vars:
    file: "{{ cassandra22x_restore_vars }}/{{ cassandra22x_environment }}/{{ inventory_hostname }}/{{ snapshot_incremental_local_archive_yml }}"  
  delegate_to: 127.0.0.1
  
- name: "create a blank list of all snapshot_keyspace_ymls for the snapshot_{{ snapshot_uuid }}"
  set_fact:
    snapshot_keyspace_ymls: []

- name: "build a list of all the snapshot_keyspace_ymls for the snapshot_{{ snapshot_uuid }}"
  set_fact:
    snapshot_keyspace_ymls: "{{ snapshot_keyspace_ymls }} + [ 'snapshot_{{ snapshot_uuid }}_{{ item }}.yml' ]"
  with_items: "{{ keyspace_names }}"

- name: loop role cassandra22x_snapshot_incremental_local_archive_for_keyspace
  include_role: 
    name: cassandra22x_snapshot_incremental_local_archive_for_keyspace
  loop: "{{ snapshot_keyspace_ymls|zip(next_snapshot_keyspace_ymls)|list }}"
  loop_control:
    loop_var: snapshot_keyspace_yml_list