---
- name: nodetool statusbinary
  command: "nodetool -u {{ cassandra22x_remote_jmx_user }} -pw {{ cassandra22x_remote_jmx_pass}} statusbinary"
  register: statusbinary
  ignore_errors: yes

- name: nodetool statusgossip
  command: "nodetool -u {{ cassandra22x_remote_jmx_user }} -pw {{ cassandra22x_remote_jmx_pass}} statusgossip"
  register: statusgossip
  ignore_errors: yes

- name: nodetool statushandoff
  command: "nodetool -u {{ cassandra22x_remote_jmx_user }} -pw {{ cassandra22x_remote_jmx_pass}} statushandoff"
  register: statushandoff
  ignore_errors: yes
    
- import_tasks: stop_cassandra.yml
  when: statusbinary.stdout == "running" and
        statusgossip.stdout == "running" and
        statushandoff.stdout == "running"

- name: include the snapshot yaml file per node
  include_vars:
    file: "{{ cassandra22x_restore_vars }}/{{ cassandra22x_src_environment }}/{{ cassandra22x_src_cluster_node }}/{{ snapshot_yml }}"

- name: "set_fact snapshot_name = snapshot_{{ snapshot_uuid }}"
  set_fact:
    snapshot_name: "snapshot_{{ snapshot_uuid }}"

- import_tasks: deploy_ring_tokens.yml
- import_tasks: remove_system.yml
- import_tasks: start_cassandra.yml