---
# original pure Ansible rsync
# - name: "rsync cassandra22x_remote_archive_path_archived_logs/{{ snapshot_name }}*.* to cassandra22x_local_archive_path_archived_logs"
  # synchronize:
    # src: "{{ cassandra22x_remote_archive_path_archived_logs }}/"
    # dest: "{{ cassandra22x_local_archive_path_archived_logs }}"
    # rsync_opts:
        # - "--bwlimit={{ cassandra22x_rsync_bwlimit }}"
        # - "--no-motd"
        # - "--include={{ snapshot_name }}*{{ cassandra22x_local_archive_file_ext }}"
        # - "--exclude=*"
  # delegate_to: "{{ inventory_hostname }}"

# faster bash rsync
- name: "rsync {{ snapshot_name }} metadata from cassandra22x_remote_archive_path_archived_logs to cassandra22x_local_archive_path_archived_logs"
  script: rsync_include_exclude_src_dest.sh {{ snapshot_name }}*{{ cassandra22x_local_archive_file_ext }} {{ cassandra22x_remote_archive_path_archived_logs }}/ {{ cassandra22x_local_archive_path_archived_logs }}