---
# dc configuration
# name of the cassandra datacenter
cassandra22x_cluster_dc: datacenter2201

## archive management
# archive variables - gz <= ansible default
cassandra22x_local_archive_format: tar
cassandra22x_local_archive_file_ext: ".tar"
# cassandra22x_local_archive_format: gz
# cassandra22x_local_archive_file_ext: ".tar.gz"
# cassandra22x_local_archive_format: bz2
# cassandra22x_local_archive_file_ext: ".tar.bz2"
# cassandra22x_local_archive_format: xz
# cassandra22x_local_archive_file_ext: ".tar.xz"

# local archive paths for keyspace snapshot on node(s) archives and metadata snapshot on node(s) archives
cassandra22x_local_archive_path: "{{ cassandra22x_var_path }}/archive"
cassandra22x_local_archive_path_archived_logs: "{{ cassandra22x_local_archive_path }}/archived_logs"
cassandra22x_local_archive_path_archived_ansible_restore_vars: "{{ cassandra22x_local_archive_path }}/ansible_cassandra22x_restore_vars"

## remote storage management
# nfs mount and node remote archive root
cassandra22x_remote_archive_nfs_mount: "{{ cassandra22x_nfs_client_mount }}/cassandra22x/{{ cassandra22x_environment }}/{{ cassandra22x_cluster_name }}/{{ inventory_hostname }}"

# remote archive paths for keyspace snapshot on node(s) archives and metadata snapshot on node(s) archives
cassandra22x_remote_archive_path: "{{ cassandra22x_remote_archive_nfs_mount }}{{ cassandra22x_local_archive_path }}"
cassandra22x_remote_archive_path_archived_logs: "{{ cassandra22x_remote_archive_path }}/archived_logs"
cassandra22x_remote_archive_path_archived_ansible_restore_vars: "{{ cassandra22x_remote_archive_path }}/ansible_cassandra22x_restore_vars"

## restore variables
# dest cluster node that will deploy schema
cassandra22x_dest_cluster_node_schema: cass10.deltakappa.com
# src cluster node supplying schema
cassandra22x_src_cluster_node_schema: cass1.deltakappa.com

## restore variables for a foregin cluster src
# foregin cluster src 
cassandra22x_src_cluster_var_path: /var/lib/cassandra
cassandra22x_src_cluster_local_archive_path: "{{ cassandra22x_src_cluster_var_path }}/archive"
cassandra22x_src_cluster_archive_format: tar
cassandra22x_src_cluster_archive_file_ext: ".tar"
cassandra22x_src_cluster_nfs_server_path: /var/nfsshare/
cassandra22x_src_cluster_nfs_client_mount: "/mnt/nfs/{{ cassandra22x_src_cluster_nfs_server }}/var/nfsshare"
cassandra22x_src_cluster_remote_archive_nfs_mount: "{{ cassandra22x_src_cluster_nfs_client_mount }}/cassandra22x/{{ cassandra22x_src_environment }}/{{ cassandra22x_src_cluster_name }}/{{ cassandra22x_src_cluster_node }}" 

# remote archive paths for keyspace snapshot on node(s) archives and metadata snapshot on node(s) archives for a foregin cluster src
cassandra22x_src_cluster_remote_archive_path: "{{ cassandra22x_src_cluster_remote_archive_nfs_mount }}/{{ cassandra22x_src_cluster_local_archive_path }}"
cassandra22x_src_cluster_remote_archive_path_archived_logs: "{{ cassandra22x_src_cluster_remote_archive_path }}/archived_logs"
cassandra22x_src_cluster_remote_archive_path_archived_ansible_restore_vars: "{{ cassandra22x_src_cluster_remote_archive_path }}/ansible_cassandra22x_restore_vars"

# restore variables for the local cluster dest
cassandra22x_local_archive_path_for_src_environment_cluster_node: "{{ cassandra22x_local_archive_path }}/{{ cassandra22x_src_environment }}/{{ cassandra22x_src_cluster_name }}/{{ cassandra22x_src_cluster_node }}"