---
- name: include the snapshot_keyspace yaml file per node
  include_vars:
    file: "{{ cassandra22x_restore_vars }}/{{ cassandra22x_environment }}/{{ inventory_hostname }}/{{ snapshot_keyspace_yml }}"

- import_tasks: refresh_column_families_for_keyspace.yml