---
# ansible-playbook /etc/ansible/playbooks/cassandra22x/operate_snapshot_rotation.yml --extra-vars "target=ansible_inventory_hosts snapshot_uuid=$(uuidgen)"
- hosts: "{{ target | default('FAIL') }}"
  gather_facts: false
  any_errors_fatal: true

  vars:
    snapshot_yml_list: []
    
  pre_tasks:
    - name: "find snapshot_ymls {{ cassandra22x_restore_vars }}/{{ cassandra22x_environment }}/{{ inventory_hostname }}"
      find:
        paths: "{{ cassandra22x_restore_vars }}/{{ cassandra22x_environment }}/{{ inventory_hostname }}"
        patterns: 'snapshot_[a-f0-9]{8}-?[a-f0-9]{4}-?4[a-f0-9]{3}-?[89ab][a-f0-9]{3}-?[a-f0-9]{12}.yml'
        use_regex: yes
      register: found_snapshot_yml
      delegate_to: 127.0.0.1
      no_log: true      

    - name: "build the list of snapshot_ymls per cassandra node"
      set_fact: 
        snapshot_yml_list: "{{ snapshot_yml_list }} + [ '{{ item.path }}' ]"
      with_items: "{{ found_snapshot_yml.files | sort(attribute='mtime',reverse=true) }}"
      when: found_snapshot_yml.matched > 0
      no_log: true

  roles:
    - cassandra22x_configure_paths
    - cassandra22x_snapshot
    - role: cassandra22x_snapshot_local_archive
      snapshot_local_archive_yml: "{{ fact_snapshot_yml }}"