---
# ansible-playbook /etc/ansible/playbooks/cassandra22x/operate_snapshot_incremental_clear_local_archive_for_keyspace.yml --extra-vars "target=ansible_inventory_hosts snapshot_keyspace_yml=snapshot_keyspace_yml next_snapshot_name=next_snapshot_name"

- hosts: "{{ target | default('FAIL') }}"
  gather_facts: false
  any_errors_fatal: true

  pre_tasks:
    - name: capture playbook start time
      set_fact:
        start_date_time_fact: "{{ now }}"
        
    # is there a previous snapshot? yes
            # clear all incremental backup files ! -newer than the previous snapshot: cassandra22x_snapshot_incremental_clear_keyspace for previous_snapshot_keyspace_yml
            # archive incremental backups for previous_snapshot_keyspace_yml: snapshot_keyspace_yml (! -newer $REFERENCE_FILE) and previous_snapshot_keyspace_yml (-newer $REFERENCE_FILE)
                # archiving should clear on archive
    
    # is there a previous snapshot? no
            # do nothing

  roles:
    - cassandra22x_snapshot_incremental_keyspace_local_archive

  post_tasks:
    - name: capture playbook end time
      set_fact: 
        end_date_time_fact: "{{ now }}"
        
    - name: operate_snapshot_incremental_clear_local_archive_for_keyspace.yml play start and end date times
      debug: 
        msg: "start_date_time: {{ start_date_time_fact }} & end_date_time: {{ end_date_time_fact }} for operate_snapshot_incremental_clear_local_archive_for_keyspace.yml playbook executed against {{ target }}"