---
# ansible-playbook /etc/ansible/playbooks/cassandra22x/operate_snapshot_get_all.yml --extra-vars "target=ansible_inventory_hosts"

- hosts: "{{ target | default('FAIL') }}"
  gather_facts: yes
  any_errors_fatal: true

  vars:
    snapshot_yml_list: []

  tasks:
    - name: "find snapshot_ymls {{ cassandra22x_restore_vars }}/{{ cassandra22x_environment }}/{{ inventory_hostname }}"
      find:
        paths: "{{ cassandra22x_restore_vars }}/{{ cassandra22x_environment }}/{{ inventory_hostname }}"
        patterns: 'snapshot_[a-f0-9]{8}-?[a-f0-9]{4}-?4[a-f0-9]{3}-?[89ab][a-f0-9]{3}-?[a-f0-9]{12}.yml'
        use_regex: yes
      register: found_snapshot_yml
      delegate_to: 127.0.0.1

    - name: "build the list of snapshot_ymls per cassandra node"
      set_fact: 
        snapshot_yml_list: "{{ snapshot_yml_list }} + [ '{{ item.path }}' ]"
      with_items: "{{ found_snapshot_yml.files | sort(attribute='mtime',reverse=true) }}"
      no_log: true
      
    - name: "show snapshot_yml_list per cassandra node"
      debug:
        msg: "{{ snapshot_yml_list }}"