---
# ansible-playbook /etc/ansible/playbooks/cassandra22x/operate_restore_local_snapshot_keyspace.yml --extra-vars "target=ansible_inventory_hosts snapshot_keyspace_yml=snapshot_keyspace_yml"

- hosts: "{{ target | default('FAIL') }}"
  gather_facts: true
  any_errors_fatal: true  

  pre_tasks:
    - name: capture playbook start time
      set_fact: 
        start_date_time_fact: "{{ now }}"  

  roles:
     - cassandra22x_restore_rsync_local_snapshots_for_keyspace
     - cassandra22x_restore_refresh_colunmfamilies_for_keyspace
     
  post_tasks:
    - name: capture playbook end time
      set_fact:
        end_date_time_fact: "{{ now }}"

    - name: cassandra22x_operate_restore_local_snapshot_keyspace.yml play start and end date times
      debug:
        msg: "start_date_time: {{ start_date_time_fact }} & end_date_time: {{ end_date_time_fact }} for cassandra22x_operate_restore_local_snapshot_keyspace.yml playbook executed against {{ target }} for {{ snapshot_keyspace_yml }}"