---
# ansible-playbook /etc/ansible/playbooks/cassandra22x/operate_snapshot.yml --extra-vars "target=ansible_inventory_hosts snapshot_uuid=$(uuidgen)"
- hosts: "{{ target | default('FAIL') }}"
  gather_facts: false
  any_errors_fatal: true
  roles:
    - cassandra22x_configure_paths
    - cassandra22x_snapshot
    - cassandra22x_snapshot_keyspace_local_archive
    - cassandra22x_snapshot_local_archive_remote_archive_rsync