---
# ansible-playbook /etc/ansible/playbooks/cassandra22x/cassandra22x_operate_stop_cluster.yml --extra-vars "target=ansible_inventory_hosts"

- hosts: "{{ target | default('FAIL') }}"
  gather_facts: yes
  any_errors_fatal: true

  pre_tasks:
    - name: capture playbook start time
      set_fact: 
        start_date_time_fact: "{{ now }}"

  roles:
     - cassandra22x_operate_stop
     
  post_tasks:
    - name: capture playbook end time
      set_fact: 
        end_date_time_fact: "{{ now }}"
        
    - name: cassandra22x_operate_stop_cluster.yml play start and end date times
      debug: 
        msg: "start_date_time: {{ start_date_time_fact }} & end_date_time: {{ end_date_time_fact }} for cassandra22x_operate_stop_cluster.yml playbook executed against {{ target }}"