---
# ansible-playbook /etc/ansible/playbooks/cassandra22x/operate_snapshot_incremental_clear_local_archive_for_keyspace.yml --extra-vars "target=ansible_inventory_hosts snapshot_keyspace_yml=snapshot_keyspace_yml next_snapshot_name=next_snapshot_name"
- hosts: "{{ target | default('FAIL') }}"
  gather_facts: false
  any_errors_fatal: true
  roles:
    - cassandra22x_snapshot_incremental_keyspace_local_archive