---
# ansible-playbook /etc/ansible/playbooks/cassandra22x/operate_snapshot.yml --extra-vars "target=ansible_inventory_hosts snapshot_uuid=$(uuidgen)"
- hosts: "{{ target | default('FAIL') }}"
  gather_facts: false
  any_errors_fatal: true
  roles:
    - cassandra22x_snapshot