---
- name: "unarchive {{ snapshot_name }} for {{ keyspace_name }}"
  unarchive:
    src: "{{ cassandra22x_local_archive_path_for_src_environment_cluster_node }}/{{ keyspace_name }}/snapshots/{{ snapshot_name }}_{{ item }}{{ cassandra22x_src_cluster_archive_file_ext }}"
    dest: "{{ cassandra22x_data_path }}/{{ keyspace_name }}/{{ item }}/snapshots"
    remote_src: yes
  with_items: "{{ column_families_disk }}"