---
- name: "include the {{ cassandra22x_log_path }}/{{ fact_snapshot_name }}_{{ keyspace_name }}.yml vars"
  include_vars:
    file: "{{ cassandra22x_restore_vars }}/{{ cassandra22x_environment }}/{{ inventory_hostname }}/{{ fact_snapshot_name }}_{{ keyspace_name }}.yml"

- name: "find the snapshot manifest.json for each column family of {{ keyspace_name }} for snapshot {{ snapshot_name }}"
  find:
    paths: "{{ cassandra22x_data_path }}/{{ keyspace_name }}/{{ item }}/snapshots/{{ snapshot_name }}/"
    patterns: "manifest.json"
  with_items: "{{ column_families_disk }}"
  register: find_column_families_disk_snapshot_manifest

- name: set fact fact_find_column_families_disk_snapshot
  set_fact: 
    fact_find_column_families_disk_snapshot: "{{ item.files | map(attribute='path') | list }}"
  with_items: "{{ find_column_families_disk_snapshot_manifest.results }}"  
  register: find_column_families_disk_snapshot
  
- name: set fact fact_find_column_families_disk_snapshot_list
  set_fact: 
    fact_find_column_families_disk_snapshot_list: "{{ find_column_families_disk_snapshot.results | map(attribute='ansible_facts.fact_find_column_families_disk_snapshot') | list | sum(start=[]) }}"

- name: "show the fact_find_column_families_disk_snapshot_list for all column families of {{ fact_snapshot_name }} & {{ keyspace_name }}"
  debug:
    msg: "{{ fact_find_column_families_disk_snapshot_list }}"

- name: set fact fact_find_column_families_disk_snapshot_manifest_mtime
  set_fact: 
    fact_find_column_families_disk_snapshot_manifest_mtime: "{{ item.files | map(attribute='mtime') | list }}"
  with_items: "{{ find_column_families_disk_snapshot_manifest.results }}"  
  register: find_column_families_disk_snapshot_manifest_mtime
  
- name: set fact fact_find_column_families_disk_snapshot_manifest_mtime_list
  set_fact: 
    fact_find_column_families_disk_snapshot_manifest_mtime_list: "{{ find_column_families_disk_snapshot_manifest_mtime.results | map(attribute='ansible_facts.fact_find_column_families_disk_snapshot_manifest_mtime') | list | sum(start=[]) }}"
  
- name: "show the fact_find_column_families_disk_snapshot_manifest_mtime_list for all column families of {{ fact_snapshot_name }} & {{ keyspace_name }}"
  debug:
    msg: "{{ fact_find_column_families_disk_snapshot_manifest_mtime_list }}"


# - name: "get all column family names for the {{ keyspace_name }} keyspace on the cassandra node"
  # script: get_columnfamilies_for_keyspace.py --keyspace_name {{ keyspace_name }}  --contact_points {{ inventory_hostname }} --username {{ cassandra22x_ansible_superuser }} --password {{ cassandra22x_ansible_superuser_password }}
  # register: get_columnfamilies_for_keyspace

# - name: "save the column_families_snapshot_manifest_json_mtime variable to {{ cassandra22x_log_path }}/{{ fact_snapshot_name }}_{{ keyspace_name }}.yml for each cassandra node"
  # lineinfile:
    # path: "{{ cassandra22x_log_path }}/{{ fact_snapshot_name }}_{{ keyspace_name }}.yml"
    # line: "column_families_snapshot_manifest_json_mtime:"

# - name: "metadata snapshot the column families on disk names to the column_families_disk variable to the snapshot yaml file for the {{ keyspace_name }} keyspace on each cassandra node"
  # lineinfile:
    # path: "{{ cassandra22x_log_path }}/{{ fact_snapshot_name }}_{{ keyspace_name }}.yml"
    # line: "{{ get_columnfamilies_for_keyspace.stdout }}"

# - name: "get all column family on disk names for the {{ keyspace_name }} keyspace on the cassandra node"
  # script: get_columnfamilies_ondisk_for_keyspace.py --keyspace_name {{ keyspace_name }}  --contact_points {{ inventory_hostname }} --username {{ cassandra22x_ansible_superuser }} --password {{ cassandra22x_ansible_superuser_password }}
  # register: get_columnfamilies_ondisk_for_keyspace
    
# - name: "save the column_families_disk variable to the {{ cassandra22x_log_path }}/{{ fact_snapshot_name }}_{{ keyspace_name }}.yml on each cassandra node"
  # lineinfile:
    # path: "{{ cassandra22x_log_path }}/{{ fact_snapshot_name }}_{{ keyspace_name }}.yml"
    # line: "column_families_disk:"

# - name: "metadata snapshot the column family names to the column_families_disk variable to the snapshot yaml file for the {{ keyspace_name }} keyspace on each cassandra node"
  # lineinfile:
    # path: "{{ cassandra22x_log_path }}/{{ fact_snapshot_name }}_{{ keyspace_name }}.yml"
    # line: "{{ get_columnfamilies_ondisk_for_keyspace.stdout }}"