---
- name: "find the snapshot manifest.json in {{ cassandra22x_data_path }}/{{ keyspace_name }}/{{ column_families_disk_name }}/snapshots/{{ snapshot_name }}/"
  find:
    paths: "{{ cassandra22x_data_path }}/{{ keyspace_name }}/{{ column_families_disk_name }}/snapshots/{{ snapshot_name }}/"
    patterns: "manifest.json"
  register: found_keyspace_snapshot_manifest

- name: "find the backup {{ cassandra22x_data_path }}/{{ keyspace_name }}/{{ column_families_disk_name }}/backups"
  find:
    paths: "{{ cassandra22x_data_path }}/{{ keyspace_name }}/{{ column_families_disk_name }}/"
    patterns: "backups"
    file_type: directory
  register: found_keyspace_backup_directory
  
- name: set fact fact_found_keyspace_snapshot_manifest
  set_fact:    
    fact_found_keyspace_snapshot_manifest: "{{ item.path }}"
  with_items: "{{ found_keyspace_snapshot_manifest.files }}"
  when: found_keyspace_snapshot_manifest.matched == 1 and
        found_keyspace_backup_directory.matched == 1  

- name: "create {{ cassandra22x_local_archive_path }}/{{ keyspace_name }}/backups"
  file:
    path: "{{ cassandra22x_local_archive_path }}/{{ keyspace_name }}/backups"
    state: directory
    owner: root
    group: root
    mode: "{{ cassandra22x_root_default_directory_mode }}"
  when: found_keyspace_snapshot_manifest.matched == 1 and
        found_keyspace_backup_directory.matched == 1

- name: "find the {{ next_snapshot_name }} in {{ cassandra22x_data_path }}/{{ keyspace_name }}/{{ column_families_disk_name }}/snapshots/"
  find:
    paths: "{{ cassandra22x_data_path }}/{{ keyspace_name }}/{{ column_families_disk_name }}/snapshots/"
    patterns: "{{ next_snapshot_name }}"
    file_type: directory
  register: found_keyspace_column_family_next_snapshot

- name: "find the snapshot manifest.json in {{ cassandra22x_data_path }}/{{ keyspace_name }}/{{ column_families_disk_name }}/snapshots/{{ next_snapshot_name }}/"
  find:
    paths: "{{ cassandra22x_data_path }}/{{ keyspace_name }}/{{ column_families_disk_name }}/snapshots/{{ next_snapshot_name }}/"
    patterns: "manifest.json"
  register: found_keyspace_next_snapshot_manifest

- name: set fact fact_found_keyspace_next_snapshot_manifest
  set_fact:    
    fact_found_keyspace_next_snapshot_manifest: "{{ item.path }}"
  with_items: "{{ found_keyspace_next_snapshot_manifest.files }}"
  when: found_keyspace_snapshot_manifest.matched == 1 and
        found_keyspace_backup_directory.matched == 1 and
        found_keyspace_column_family_next_snapshot.matched == 1 and
        found_keyspace_next_snapshot_manifest.matched == 1

- name: "archive & remove incremental backup files for the {{ snapshot_name }} for {{ keyspace_name }}.{{ column_families_disk_name }} using {{ next_snapshot_name }} as the next snapshot"
  script: find_archive_delete_backups_for_snapshot_w_next.sh {{ fact_found_keyspace_snapshot_manifest | regex_replace('/snapshots/snapshot_[a-f0-9]{8}-?[a-f0-9]{4}-?4[a-f0-9]{3}-?[89ab][a-f0-9]{3}-?[a-f0-9]{12}/manifest.json', '/backups') }} {{ fact_found_keyspace_snapshot_manifest }} {{ fact_found_keyspace_next_snapshot_manifest }} {{ cassandra22x_local_archive_path }}/{{ keyspace_name }}/backups/{{ snapshot_name }}_{{ column_families_disk_name }}{{ cassandra22x_src_cluster_archive_file_ext }} {{ cassandra22x_src_cluster_archive_format }}
  when: found_keyspace_snapshot_manifest.matched == 1 and
        found_keyspace_backup_directory.matched == 1 and
        found_keyspace_column_family_next_snapshot.matched == 1 and
        found_keyspace_next_snapshot_manifest.matched == 1

- name: "archive & remove incremental backup files for the {{ snapshot_name }} for {{ keyspace_name }}.{{ column_families_disk_name }} that no longer exist using {{ next_snapshot_name }} as the next snapshot"
  script: find_archive_delete_backups_for_snapshot.sh {{ fact_found_keyspace_snapshot_manifest | regex_replace('/snapshots/snapshot_[a-f0-9]{8}-?[a-f0-9]{4}-?4[a-f0-9]{3}-?[89ab][a-f0-9]{3}-?[a-f0-9]{12}/manifest.json', '/backups') }} {{ fact_found_keyspace_snapshot_manifest }} {{ cassandra22x_local_archive_path }}/{{ keyspace_name }}/backups/{{ snapshot_name }}_{{ column_families_disk_name }}{{ cassandra22x_src_cluster_archive_file_ext }} {{ cassandra22x_src_cluster_archive_format }}
  when: found_keyspace_snapshot_manifest.matched == 1 and
        found_keyspace_backup_directory.matched == 1 and
        found_keyspace_column_family_next_snapshot.matched == 0 and
        found_keyspace_next_snapshot_manifest.matched == 0