---
- name: "nodetool clearsnapshot -t {{ snapshot_name}} {{ keyspace_name }}"
  script: nodetool-clearsnapshot.sh {{ cassandra22x_ansible_superuser }} {{ cassandra22x_ansible_superuser_password }} {{ snapshot_name }} {{ keyspace_name }}

- name: "clear {{ cassandra22x_log_path }} snapshot: {{ snapshot_name}} for keyspace: {{ keyspace_name }} metadata"
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ cassandra22x_log_path }}/{{ snapshot_name}}_{{ keyspace_name }}.log"
    - "{{ cassandra22x_log_path }}/{{ snapshot_name}}_{{ keyspace_name }}.yml"    
    - "{{ cassandra22x_log_path }}/{{ snapshot_name}}_{{ keyspace_name }}_schema.cql"
  
- name: "clear {{ cassandra22x_local_archive_path }}/{{ keyspace_name }}/snapshots/{{ snapshot_name }}.tar"
  file:
    path: "{{ cassandra22x_local_archive_path }}/{{ keyspace_name }}/snapshots/{{ snapshot_name }}.tar"
    state: absent
  
- name: "clear {{ cassandra22x_restore_vars }}/{{ cassandra22x_environment }}/{{ inventory_hostname }}/{{ snapshot_name }}_{{ keyspace_name }}.yml"
  file:
    path: "{{ cassandra22x_restore_vars }}/{{ cassandra22x_environment }}/{{ inventory_hostname }}/{{ snapshot_name }}_{{ keyspace_name }}.yml"
    state: absent
  delegate_to: 127.0.0.1
  
- name: "clear {{ cassandra22x_restore_vars }}/{{ cassandra22x_environment }}/{{ inventory_hostname }}/{{ snapshot_name }}_{{ keyspace_name }}.yml"
  file:
    path: "{{ cassandra22x_restore_vars }}/{{ cassandra22x_environment }}/{{ inventory_hostname }}/{{ snapshot_name }}_{{ keyspace_name }}_new_schema.yml"
    state: absent
  delegate_to: 127.0.0.1  