---
- name: "rsync hardlink local snapshot files to the new schema location for keyspace: {{ keyspace_name }}"
  synchronize:
    src: "{{ cassandra22x_data_path }}/{{ keyspace_name }}/{{ item.0 }}/snapshots/{{ snapshot_name }}/"
    dest: "{{ cassandra22x_data_path }}/{{ keyspace_name }}/{{ item.1 }}/"
    rsync_opts:
        - "--no-motd"
        - "--exclude=manifest.json"
        - "--link-dest={{ cassandra22x_data_path }}/{{ keyspace_name }}/{{ item.1 }}"
  with_together: 
        - "{{ column_families_disk }}"
        - "{{ column_families_disk_new }}"
  delegate_to: "{{ inventory_hostname }}"