---
- name: "get all column family names for the {{ keyspace_name }} keyspace on the cassandra node"
  script: get_columnfamilies_for_keyspace.py --keyspace_name {{ keyspace_name }}  --contact_points {{ inventory_hostname }} --username {{ cassandra22x_ansible_superuser }} --password {{ cassandra22x_ansible_superuser_password }}
  register: get_columnfamilies_for_keyspace

- name: "save the column_families variable to {{ cassandra22x_log_path }}/{{ fact_snapshot_name }}_{{ keyspace_name }}.yml for each cassandra node"
  lineinfile:
    path: "{{ cassandra22x_log_path }}/{{ fact_snapshot_name }}_{{ keyspace_name }}.yml"
    line: "column_families:"

- name: "metadata snapshot the column families on disk names to the column_families_disk variable to the snapshot yaml file for the {{ keyspace_name }} keyspace on each cassandra node"
  lineinfile:
    path: "{{ cassandra22x_log_path }}/{{ fact_snapshot_name }}_{{ keyspace_name }}.yml"
    line: "{{ get_columnfamilies_for_keyspace.stdout }}"

- name: "get all column family on disk names for the {{ keyspace_name }} keyspace on the cassandra node"
  script: get_columnfamilies_ondisk_for_keyspace.py --keyspace_name {{ keyspace_name }}  --contact_points {{ inventory_hostname }} --username {{ cassandra22x_ansible_superuser }} --password {{ cassandra22x_ansible_superuser_password }}
  register: get_columnfamilies_ondisk_for_keyspace
    
- name: "save the column_families_disk variable to the {{ cassandra22x_log_path }}/{{ fact_snapshot_name }}_{{ keyspace_name }}.yml on each cassandra node"
  lineinfile:
    path: "{{ cassandra22x_log_path }}/{{ fact_snapshot_name }}_{{ keyspace_name }}.yml"
    line: "column_families_disk:"

- name: "metadata snapshot the column family names to the column_families_disk variable to the snapshot yaml file for the {{ keyspace_name }} keyspace on each cassandra node"
  lineinfile:
    path: "{{ cassandra22x_log_path }}/{{ fact_snapshot_name }}_{{ keyspace_name }}.yml"
    line: "{{ get_columnfamilies_ondisk_for_keyspace.stdout }}"