---


- name: "find the snapshot manifest.json for each column family for snapshot {{ snapshot_name }}"
  find:
    paths: "{{ cass_data_path }}/{{ keyspace_name }}/{{ item }}/snapshots/{{ snapshot_name }}/"
    patterns: "manifest.json"
  with_items: "{{ column_families_disk }}"
  register: find_column_families_disk



SEARCH_ROOT=$1
REFERENCE_FILE=$2
find $SEARCH_ROOT -type f ! -newer $REFERENCE_FILE -delete









- name: set fact fact_find_column_families_disk_path
  set_fact: 
    fact_find_column_families_disk_path: "{{ item.files | map(attribute='path') | list }}"
  with_items: "{{ find_column_families_disk.results }}"  
  register: reg_fact_find_column_families_disk_path
  
- name: set fact fact_find_column_families_disk_path_results_list
  set_fact: 
    fact_find_column_families_disk_path_results_list: "{{ reg_fact_find_column_families_disk_path.results | map(attribute='ansible_facts.fact_find_column_families_disk_path') | list | sum(start=[]) }}"  

- name: create missing backup directories
  file:
    path: "{{ item | regex_replace('/snapshots/snapshot_[a-f0-9]{8}-?[a-f0-9]{4}-?4[a-f0-9]{3}-?[89ab][a-f0-9]{3}-?[a-f0-9]{12}/manifest.json', '/backups') }}"
    state: directory
    owner: cassandra
    group: cassandra
    mode: "u=rwx,g=rx,o=rx"
  loop: "{{ fact_find_column_families_disk_path_results_list }}"
  loop_control:
    label: "{{ item | regex_replace('/snapshots/snapshot_[a-f0-9]{8}-?[a-f0-9]{4}-?4[a-f0-9]{3}-?[89ab][a-f0-9]{3}-?[a-f0-9]{12}/manifest.json', '/backups') }}"
    
- name: find and remove backup files older than a snapshot
  script: find_delete_backups_older_than_snapshot.sh {{ item | regex_replace('/snapshots/snapshot_[a-f0-9]{8}-?[a-f0-9]{4}-?4[a-f0-9]{3}-?[89ab][a-f0-9]{3}-?[a-f0-9]{12}/manifest.json', '/backups') }} {{ item }}
  loop: "{{ fact_find_column_families_disk_path_results_list }}"
  loop_control:
    label: "find_delete_backups_older_than_snapshot.sh {{ item | regex_replace('/snapshots/snapshot_[a-f0-9]{8}-?[a-f0-9]{4}-?4[a-f0-9]{3}-?[89ab][a-f0-9]{3}-?[a-f0-9]{12}/manifest.json', '/backups') }} {{ item }}"