---
- name: "include the {{ cassandra22x_log_path }}/{{ fact_snapshot_name }}_{{ keyspace_name }}.yml vars"
  include_vars:
    file: "{{ cassandra22x_restore_vars }}/{{ cassandra22x_environment }}/{{ inventory_hostname }}/{{ snapshot_name }}_{{ keyspace_name }}.yml"
    
- name: "save the column_families_snapshot_manifest_json_mtime variable to {{ cassandra22x_log_path }}/{{ fact_snapshot_name }}_{{ keyspace_name }}.yml for each cassandra node"
  lineinfile:
    path: "{{ cassandra22x_log_path }}/{{ fact_snapshot_name }}_{{ keyspace_name }}.yml"
    line: "column_families_snapshot_manifest_json_mtime:"

- name: "loop update_snapshot_keyspace_columnfamilies.yml for each column family of the keyspace on the cassandra node"
  include_tasks: update_snapshot_keyspace_yml_columnfamilies_manifest_json_mtime.yml
  loop: "{{ column_families_disk }}"
  loop_control:
    loop_var: column_families_disk_name