---
- name: set snapshot_keyspace_yml facts
  set_fact:
    fact_snapshot_name: "{{ snapshot_name }}"
    fact_keyspace_name: "{{ keyspace_name }}"
    fact_column_families: "{{ column_families }}"
    fact_column_families_disk: "{{ column_families_disk }}"

- import_tasks: rsync_local_snapshot_incrementals_for_keyspace.yml
  when: next_snapshot_keyspace_yml != "none"
  
- import_tasks: rsync_local_snapshot_incrementals_for_keyspace_no_filter.yml
  when: next_snapshot_keyspace_yml == "none"