---
- name: "include the {{ cassandra22x_restore_vars }}/{{ cassandra22x_environment }}/inventory_hostname/{{ next_snapshot_keyspace_yml }} vars"
  include_vars:
    file: "{{ cassandra22x_restore_vars }}/{{ cassandra22x_environment }}/{{ inventory_hostname }}/{{ next_snapshot_keyspace_yml }}"

- name: "set next_snapshot_keyspace_yml facts"
  set_fact:
    fact_next_snapshot_name: "{{ snapshot_name }}"
    fact_next_keyspace_name: "{{ keyspace_name }}"
    fact_next_column_families: "{{ column_families }}"
    fact_next_column_families_disk: "{{ column_families_disk }}"

- name: "rsync the local snapshot incrementals {{ fact_snapshot_name }} of {{ fact_keyspace_name }}"
  include_tasks: rsync_local_snapshot_incrementals_for_keyspace_cf.yml
  loop: "{{ fact_column_families_disk|zip(column_families_disk_new)|list }}"
  loop_control:
    loop_var: column_family_disk_name_new_schema