---
- name: "create {{ cassandra22x_log_path }}/{{ fact_snapshot_name }}.yml"
  file: 
    path: "{{ cassandra22x_log_path }}/{{ fact_snapshot_name }}.yml"
    state: touch
    mode: "u+rw,g-wx,o-rwx"

- name: "update {{ cassandra22x_log_path }}/{{ fact_snapshot_name }}.yml with snapshot_name metadata"
  lineinfile:
    path: "{{ cassandra22x_log_path }}/{{ fact_snapshot_name }}.yml"
    line: "snapshot_name: {{ fact_snapshot_name }}"

- name: "update {{ cassandra22x_log_path }}/{{ fact_snapshot_name }}.yml with keyspace_names metadata"
  lineinfile:
    path: "{{ cassandra22x_log_path }}/{{ fact_snapshot_name }}.yml"
    line: "keyspace_names:"

- name: "update {{ cassandra22x_log_path }}/{{ fact_snapshot_name }}.yml with fact_snapshot_keyspace_list items metadata"
  lineinfile:
    path: "{{ cassandra22x_log_path }}/{{ fact_snapshot_name }}.yml"
    line: "    - {{ item }}"
  with_items: "{{ fact_snapshot_keyspace_list }}"
  no_log: true  

- name: "create {{ cassandra22x_log_path }}/{{ fact_snapshot_name }}_item.yml file for each keyspace (item) on the C* node for the snapshot {{ fact_snapshot_name }}_item for each keyspace (item)"
  file: 
    path: "{{ cassandra22x_log_path }}/{{ fact_snapshot_name }}_{{ item }}.yml"
    state: touch
    mode: "u+rw,g-wx,o-rwx"
  with_items: "{{ fact_snapshot_keyspace_list }}"
  no_log: true  

- name: "update {{ cassandra22x_log_path }}/{{ fact_snapshot_name }}_item.yml file for each keyspace (item) on the C* node for the snapshot {{ fact_snapshot_name }}_item for each keyspace (item) snapshot metadata"
  lineinfile:
    path: "{{ cassandra22x_log_path }}/{{ fact_snapshot_name }}_{{ item }}.yml"
    line: "snapshot_name: {{ fact_snapshot_name }}"
  with_items: "{{ fact_snapshot_keyspace_list }}"
  no_log: true  

- name: "update {{ cassandra22x_log_path }}/{{ fact_snapshot_name }}_item.yml file for each keyspace (item) on the C* node for the snapshot {{ fact_snapshot_name }}_item for each keyspace (item) keyspace metadata"
  lineinfile:
    path: "{{ cassandra22x_log_path }}/{{ fact_snapshot_name }}_{{ item }}.yml"
    line: "keyspace_name: {{ item }}"
  with_items: "{{ fact_snapshot_keyspace_list }}"
  no_log: true  