---
- name: "create {{ cassandra22x_log_path }}/{{ fact_snapshot_name }}_{{ keyspace_name }}_schema.cql"
  file: 
    path: "{{ cassandra22x_log_path }}/{{ fact_snapshot_name }}_{{ keyspace_name }}_schema.cql"
    state: touch
    mode: "u+rw,g-wx,o-rwx"

- name: "get keyspace schema for {{ keyspace_name }} keyspace"
  script: get_schema_for_keyspace.py --keyspace_name {{ keyspace_name }}  --contact_points {{ inventory_hostname }} --username {{ cassandra22x_ansible_superuser }} --password {{ cassandra22x_ansible_superuser_password }}
  register: get_schema_for_keyspace
  
- name: "create {{ cassandra22x_log_path }}/{{ fact_snapshot_name }}_{{ keyspace_name }}_schema.cql"
  lineinfile:
    path: "{{ cassandra22x_log_path }}/{{ fact_snapshot_name }}_{{ keyspace_name }}_schema.cql"
    line: "{{ item }}"
  with_items: "{{ get_schema_for_keyspace.stdout }}"
  no_log: true