---
- name: "create missing {{ cassandra22x_local_archive_path }} for each keyspace/snapshots"
  file:
    path: "{{ cassandra22x_local_archive_path }}/{{ item }}/snapshots"
    state: directory
    owner: root
    group: root    
    mode: "{{ cassandra22x_root_default_directory_mode }}"
  with_items: "{{ keyspace_names }}"