---
- name: include the snapshot yaml file per node
  include_vars:
    file: "{{ cassandra22x_restore_vars }}/{{ cassandra22x_environment }}/{{ inventory_hostname }}/{{ snapshot_yml }}"
  delegate_to: 127.0.0.1
  
- name: "set_fact snapshot_name = snapshot_{{ snapshot_uuid }}"
  set_fact:
    snapshot_name: "snapshot_{{ snapshot_uuid }}"

- import_tasks: configure_local_archive_paths.yml
- import_tasks: local_archive_snapshot.yml