---
- name: "include {{ cassandra22x_restore_vars }}/{{ cassandra22x_environment }}/inventory_hostname/{{ snapshot_keyspace_yml }} vars"
  include_vars:
    file: "{{ cassandra22x_restore_vars }}/{{ cassandra22x_environment }}/{{ inventory_hostname }}/{{ snapshot_keyspace_yml }}"

- import_tasks: configure_local_archive_paths.yml
- import_tasks: rsync_remote_archive_snapshot_incremental.yml