---
# original pure Ansible rsync
# - name: "rsync {{ cassandra22x_remote_archive_path }}/{{ keyspace_name }} to {{ cassandra22x_local_archive_path }}/{{ keyspace_name }}"
  # synchronize:
    # src: "{{ cassandra22x_remote_archive_path }}/{{ keyspace_name }}/"
    # dest: "{{ cassandra22x_local_archive_path }}/{{ keyspace_name }}"
    # rsync_opts:
        # - "--bwlimit={{ cassandra22x_rsync_bwlimit }}"
        # - "--no-motd"
  # delegate_to: "{{ inventory_hostname }}"

# faster bash rsync
- name: "rsync {{ cassandra22x_remote_archive_path }}/{{ keyspace_name }}/backups to {{ cassandra22x_local_archive_path }}/{{ keyspace_name }}/backups"
  script: rsync_remote_archive_snapshot_incremental.sh {{ snapshot_name }}*{{ cassandra22x_local_archive_file_ext }} {{ cassandra22x_remote_archive_path }}/{{ keyspace_name }}/backups/ {{ cassandra22x_local_archive_path }}/{{ keyspace_name }}/backups