--- 
- name: "include the {{ cassandra22x_restore_vars }}/{{ cassandra22x_src_environment }}/{{ cassandra22x_src_cluster_node }}/{{ snapshot_yml }} vars"
  include_vars:
    file: "{{ cassandra22x_restore_vars }}/{{ cassandra22x_src_environment }}/{{ cassandra22x_src_cluster_node }}/{{ snapshot_yml }}"

- import_tasks: local_unarchive_snapshot_logs.yml